spring:
  application:
    name: config-server

  cloud:
    config:
      server:
#        git:
#          uri: "https://github.com/.....test"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
#        vault:
#          host: localhost
#          port: 8200
#          scheme: http
#          backend: secret
#          kvVersion: 2
#          authentication: TOKEN
#          token: ${VAULT_TOKEN}
#          skipSslValidation: true
#          profile-separator: /

  profiles:
    active: vault

server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

# Define your Vault token here
VAULT_TOKEN: test-tokem
