services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"  # Specify ports in quotes for consistency
    volumes:
      - mongo:/data/db  # Corrected volume path for MongoDB data storage
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mariadb:
    image: mariadb
    container_name: mariadb_server
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin  # Replace with your desired root password
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mongo:
  mariadb_data: